export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const FIND_POST = 'FIND_POST'
export const SET_AUTH = 'SET_AUTH'
export const LOCAL_STORAGE_POST_NAME = 'TO_DO_TASK'
export const LOAD_POST = 'LOAD_POST'
export const SORT_POST = 'SORT_POST'
